name: Some GitHub action
on: [push]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: run booklet
        run: python3 booklet_numbering.py 4

  test_c:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run hello
        working-directory: c
        run: |
          make
          ./hello
